--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Pedhot-Dev/TeleportAll
build-by-default: true
branches:
- master
projects:
  TeleportAll:
    path: ""
    libs:
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: ^2.0.0
...
